services:
  adguard-sync:
    image: ghcr.io/bakito/adguardhome-sync:latest
    container_name: adguard-sync
    env_file:
      - ~/.secrets/adguard_home_sync/.env
    environment:
      - ORIGIN_URL=http://10.10.10.50 # Master
      - REPLICA_URL=http://10.10.10.55
      - CRON=*/5 * * * * # Sync every 5 minutes
      - LOG_LEVEL=info
    restart: unless-stopped
