#!/usr/bin/env bash

library_dir="/srv/music/library"
data_dir="/srv/navidrome/data"
syncthing_dir="/srv/syncthing"

if [[ -d "$library_dir" ]]; then
	echo "$library_dir already exists"
else
	sudo mkdir -p "$library_dir"
	sudo chown -R 1000:1000 /srv/music
	echo "$library_dir created succesfully"
	
fi

if [[ -d "$data_dir" ]]; then
        echo "$data_dir already exists"
else
        sudo mkdir -p "$data_dir"
	echo "$data_dir created succesfully"
fi

if [[ -d "$syncthing_dir" ]]; then
        echo "$syncthing_dir already exists"
else
        sudo mkdir -p "$syncthing_dir"
	echo "$syncthing_dir created succesfully"
fi
