http:
  routers:
    # Router: Navidrome
    navidrome:
      rule: "Host(`music.kacper-nxn.pl`)"
      entryPoints:
        - web
      service: navidrome-svc

    # Router: Seafile
    seafile:
      rule: "Host(`seafile.kacper-nxn.pl`)"
      entryPoints:
        - web
      service: seafile-svc
      middlewares:
        - seafile-headers

    # Router: Vaultwarden
    vaultwarden:
      rule: "Host(`warden.kacper-nxn.pl`)"
      entryPoints:
        - web
      service: vaultwarden-svc

    forgejo:
      rule: "Host(`forgejo.kacper-nxn.pl`)"
      entryPoints:
        - web
      service: forgejo-svc

  #  Middlewares
  middlewares:
    seafile-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "http"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
          - "X-Forwarded-For"

  # Services
  services:
    navidrome-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.115:4533"

    seafile-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.115:9000"
        passHostHeader: true

    vaultwarden-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.115:8000"
        passHostHeader: true

    forgejo-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.249:3000"
        passHostHeader: true
