http:
  routers:
    navidrome:
      rule: "Host(`music.kacper-nxn.pl`)"
      entrypoints: ["web"]
      service: navidrome-svc
    seafile:
      rule: "Host(`seafile.kacper-nxn.pl`)"
      entrypoints: ["web"]
      service: seafile-svc
      middlewares:
        - seafile-headers

  middlewares:
    seafile-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "http"
          X-Real-IP: ""
        hostsProxyHeaders:
          - "X-Forwarded-Host"
          - "X-Forwarded-For"

  services:
    navidrome-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.115:4533"
    seafile-svc:
      loadBalancer:
        servers:
          - url: "http://10.10.10.115:9000"
        passHostHeader: true