global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

# pve-exporter job
  - job_name: "pve-exporter"
    metrics_path: /pve
    params:
      module: [default]
      cluster: ["1"]
      node: ["1"]
    static_configs:
    
      - targets: ["10.10.10.31"]
        labels:
          nodename: "pve01"

      - targets: ["10.10.10.32"]
        labels:
          nodename: "pve02"

      - targets: ["10.10.10.33"]
        labels:
          nodename: "pve03"

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        regex: '(.+)'
        replacement: '$1:9221'
        target_label: __address__
      - source_labels: [nodename]
        target_label: instance

# node-exporter job
  - job_name: "node-exporter"
    static_configs:

    # Proxmox nodes
      - targets: ["10.10.10.31:9100"]
        labels:
          nodename: "pve01"

      - targets: ["10.10.10.32:9100"]
        labels:
          nodename: "pve02"

      - targets: ["10.10.10.33:9100"]
        labels:
          nodename: "pve03"

    # Virtual machines
      - targets: ["10.10.10.115:9100"]
        labels:
          nodename: "prox-services"
      
      - targets: ["10.10.10.107:9100"]
        labels: 
          nodename: "prox-monitoring"

      - targets: ["10.10.10.249:9100"]
        labels:
          nodename: "prox-cicd"

    # LXC containers
      - targets: ["10.10.10.200:9100"]
        labels:
          nodename: "prox-adguard"

      - targets: ["10.10.10.204:9100"]
        labels:
          nodename: "prox-gateway"
# Cadvisor job
  - job_name: "cadvisor"
    static_configs:

    # Docker containers
      - targets: ["10.10.10.115:6060"]
        labels:
          nodename: "prox-services"
      
      - targets: ["10.10.10.204:6060"]
        labels:
          nodename: "prox-gateway"
      
      - targets: ["10.10.10.107:6060"]
        labels:
          nodename: "prox-monitoring"
      
      - targets: ["10.10.10.249:6060"]
        labels:
          nodename: "prox-cicd"
