global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

# Monitored VM's and lxc containers
  - job_name: "node-exporter"
    static_configs:

    # Proxmox nodes
      - targets: ["10.10.10.31:9100"]
        labels:
          nodename: "pve01"

      - targets: ["10.10.10.32:9100"]
        labels:
          nodename: "pve02"

      - targets: ["10.10.10.33:9100"]
        labels:
          nodename: "pve03"

    # Virtual machines
      - targets: ["10.10.10.115:9100"]
        labels:
          nodename: "prox-services"
      
      - targets: ["10.10.10.189:9100"]
        labels:
          nodename: "prox-gateway"

      - targets: ["10.10.10.114:9100"]
        labels:
          nodename: "prox-tailscale"

      - targets: ["10.10.10.107:9100"]
        labels: 
          nodename: "prox-monitoring"

    # LXC containers
      - targets: ["10.10.10.200:9100"]
        labels:
          nodename: "prox-adguard"