all:
  vars:
    ansible_user: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/ansible/users').sys_user.username }}"
    ansible_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/ansible/users').sys_user.password }}"
    ansible_become_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/ansible/users').sys_user.password }}"
    ansible_ssh_private_key_file: /home/kacper/.ssh/proxmox_vms
  children:
    k3s_cluster:
      children:
        control_planes:
          hosts:
            cp_01:
              ansible_host: 10.10.10.138
    
        workers:
          hosts:
            worker_01:
              ansible_host: 10.10.10.245
            worker_02:
              ansible_host: 10.10.10.246
    
    proxmox_infra:
      children:
        proxmox_nodes:
          vars:
            ansible_user: root
          hosts:
            pve01:
              ansible_host: 10.10.10.31
            pve02:
              ansible_host: 10.10.10.32
            pve03:
              ansible_host: 10.10.10.33

        virtual_machines:
          hosts:
            prox-services:
              ansible_host: 10.10.10.115
            prox-monitoring:
              ansible_host: 10.10.10.107
            prox-cicd:
              ansible_host: 10.10.10.249

        # LXC containers
            prox-adguard-master:
              ansible_host: 10.10.10.50
            prox-adguard-backup:
              ansible_host: 10.10.10.55
            prox-gateway:
              ansible_host: 10.10.10.224
            prox-tailscale:
              ansible_host: 10.10.10.70