- name: Prepare Infrastructure
  hosts: k3s_cluster
  become: true
  roles:
    - role: bootstrap
      tags:
        - bootstrap

- name: Install k3s server
  hosts: control_planes
  become: true
  roles:
    - role: k3s-server
      tags:
        - server

- name: Install k3s agents
  hosts: workers
  vars:
    k3s_token: "{{ hostvars[groups['control_planes'][0]].k3s_node_token }}"
    k3s_url: "https://{{ hostvars[groups['control_planes'][0]].ansible_host }}:6443"
  become: true
  roles:
    - role: k3s-agent
      tags: 
        - agents


