- hosts: virtual_machines,proxmox_nodes
  become: true
  vars:
    version: "1.8.2"
    arch: "amd64"

  handlers:
    - name: Restart node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted
        daemon_reload: true
        enabled: true

  tasks:
    - name: Create node_exporter user
      ansible.builtin.user:
        name: node_exporter
        shell: /usr/sbin/nologin
        system: true
        create_home: false

    - name: Install node_exporter
      ansible.builtin.unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-{{ arch }}.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Copy binary into /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ version }}.linux-{{ arch }}/node_exporter"
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        owner: node_exporter
        group: node_exporter
        remote_src: yes

    - name: Create systemd service
      ansible.builtin.template:
        src: ../templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
      notify: Restart node_exporter

    - name: Cleanup temp files
      ansible.builtin.file:
        path: "/tmp/node_exporter-{{ version }}.linux-{{ arch }}"
        state: absent

    - name: Enable node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: true