services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://warden.kacper-nxn.pl
      - I_REALLY_WANT_VOLATILE_STORAGE=false
    volumes:
      - /srv/vaultwarden/vw-data:/data
    ports:
      - "8000:80"