services:
  homelab-hub:
    image: raidowl/homelab-hub:latest
    container_name: homelab-hub
    ports:
      - "8020:8000"
    volumes:
      - homelab_hub_data:/data
    restart: unless-stopped

volumes:
  homelab_hub_data:
    name: homelab_hub_data
