services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome 
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      ND_ENABLELEGACYAUTH: "true"
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info
    volumes:
      - /srv/navidrome/data:/data
      - /srv/music/library:/music 
