apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
