- name: k3s instalation
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Run k3s server
  ansible.builtin.command: /tmp/k3s_install.sh
  args:
    creates: /etc/systemd/system/l3s-agent.service
  environment:
    K3S_URL: "{{ k3s_url }}"
    K3S_TOKEN: "{{ k3s_token }}"

- name: Ensure that k3s is running
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true
